Error injection and fixes to resilient OpenMP execution spaces
kokkos/kokkos-resilience pull request #71
Opened 2024-09-18 19:46 UTC by ElisabethGiem

An omnibus PR to bring Kokkos Resilience up to date with execution space work.

- Adds error injection for one and two-dimensional ResOMP space views
- Changes behavior of triple modular redundancy and dual modular redundancy cmake options from previous
- Changes kernel fusion cmake option to accept WorkTag if present
- Various error and bugfixes
- Removes (some) unnecessary comments

Apologies for the mega PR, smaller PRs in the future!

2024-10-22 17:01 UTC, nmm0 commented
Can you rebase this on main to get the CI fix?

2024-11-13 22:20 UTC, nmm0 requested changes
Initial part of the review, will continue with more

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      std::cout << "Error finding error_rate. Were global error settings enabled?\n";
I'm not sure we need this output

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      std::cout << "In MakeWrapper void WorkTag branch." << std::endl;
Can remove this

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      std::cout << "In MakeWrapper WorkTag branch." << std::endl;
Same here

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +    //TODO: Cmake option reexecution_max off or number, enable spare view in the subscriber
This should be made into a github issue and removed as a comment

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      //std::cout << "Test print if triggered repeat from too many errors.\n";
remove dead code

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      std::cout << "Right before MakeWrapper" <<std::endl;
Remove extraneous print

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +/*      auto wrapper_functor = [&](m_worktag ,auto i){
Remove dead code

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +#ifdef KR_ENABLE_TMR
Maybe we should check that only one of TMR, DMR, or WRAPPER are enabled

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      //KokkosResilience::inject_error_duplicates();
This should be behind a define

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      KokkosResilience::inject_error_duplicates();
This should be behind a define/cmake option

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      // TODO: separate into fusion cmake option, enabled on dmr or tmr
Move TODO comment to a github issue

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      KokkosResilience::inject_error_duplicates();
This should be guarded by a define/cmake option

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      // TODO: cmake option
Move TODO comment to an issue

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      Impl::ParallelFor< decltype(m_functor) , surrogate_policy, Kokkos::OpenMP > closure2(m_functor_1 , wrapper_policy );
I think we need to make MDRangePolicy have feature partiy with regular range policy; or if we want remove this from the PR and have in a different one

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
>      }// while (!success & repeats left)
should remove dead code here

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +      }// while (!success & repeats left)
remove dead code here

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResParallel.hpp
> +class ParallelReduce< CombinedFunctorReducerType
Is this guy working properly? If not lets omit from the PR

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResSubscriber.hpp
> +inline static std::chrono::duration<long int, std::ratio<1, 1000000000>> total_error_time{};
```suggestion
inline static std::chrono::duration<long int, std::nano> elapsed_seconds{};
inline static std::chrono::duration<long int, std::nano> total_error_time{};
```

2024-11-13 22:20 UTC, nmm0 commented on src/resilience/openMP/OpenMPResSubscriber.hpp
> +struct ETimer{
```suggestion
struct ErrorTimerSettings{
```

2025-03-25 23:37 UTC, Matthew-Whitlock requested changes
You can probably ignore some of this at your discretion

2025-03-25 23:37 UTC, Matthew-Whitlock commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +#endif
Something like this?
```suggestion
  for(int copy = 0; copy < res.duplicate_count; copy++){
    for(int dim = 0; dim < View::rank; dim++){
      if(original.extent(dim) != res.copy[copy].extent(dim)){
        set_duplicate_view(res.copy[copy], original, copy);
        break;
      }
    }
  }
```

2025-03-25 23:37 UTC, Matthew-Whitlock commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +      handler((size_t)success);
Just caught that you switched to just using the boolean due to reviews - in that case, the description in ErrorHandler.hpp needs to be updated

2025-03-25 23:48 UTC, Matthew-Whitlock commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +#endif
Actually I don't think this would fix the DMR issue, since the duplicate will be 1 until after this function is called.

2025-03-25 23:49 UTC, Matthew-Whitlock commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +        Kokkos::deep_copy(self, other);
Should the resize checks in `get_duplicate_for` just go right before this `deep_copy` instead?

2025-03-31 14:55 UTC, nmm0 reviewed
Another batch of comments

2025-03-31 14:55 UTC, nmm0 commented on src/resilience/backend/StdFileBackend.cpp
> +#endif
Yes I think you should revert the changes to unrelated files

2025-03-31 14:55 UTC, nmm0 commented on src/resilience/data_space/StdFileSpace.hpp
> +#include "resilience/filesystem/ExternalIOInterface.hpp"
Same here, omit from PR

2025-03-31 14:55 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +      handler((size_t)success);
```suggestion
      handler(static_cast<size_t>(success));
```

2025-03-31 14:55 UTC, nmm0 commented on tests/TestMain.cpp
> +  {
I don't quite get this change

2025-03-31 14:55 UTC, nmm0 commented on tests/TestMiniMD.cpp
> +  //KokkosResilience::global_error_settings = KokkosResilience::Error(0.1);
This file needs some cleanup, i.e. dead code (commented out code) and so on

2025-05-01 21:21 UTC, Matthew-Whitlock commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +        Kokkos::deep_copy(self, other);
This comment was aimed at addressing the problem commented here: https://github.com/kokkos/kokkos-resilience/blob/232a76387c56f9dcb145db03e0149c2bd03f39d5/src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp#L458

Rather than checking for a resize a few lines up in `get_duplicate_for(other);`, since it just checks the first view every time, should you check for a resize in this function when you know which duplicate you are about to use?

2025-05-06 15:36 UTC, nmm0 reviewed
Another pass! Sorry it's taken so long!

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +    if (KokkosResilience::global_error_settings){
```suggestion
    if (global_error_settings){
```

The namespace qualification is a bit redundant here

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +  auto MakeWrapper (int64_t work_size, int64_t offset, const FunctorType &m_functor_0, const FunctorType &m_functor_1) const{
```suggestion
  auto make_wrapper(int64_t work_size, int64_t offset, const FunctorType &functor_copy_0, const FunctorType &functor_copy_1) const {
```

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +    }else if constexpr (!std::is_void_v<WorkTag>)
The formatting is a bit inconsistent here, can you run clang-format on the files? (We have a .clang-format file)

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
>        auto m_functor_1 = m_functor;
I guess I didn't notice this before but a better name would be something like `functor_copy_0` and `functor_copy_1`, or even better yet an array like:

```cpp
auto functor_copies = std::array{ m_functor, m_functor };
```

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +      auto wrapper_functor = MakeWrapper (work_size, offset, m_functor_0, m_functor_1);
```suggestion
      auto wrapper_functor = make_wrapper(work_size, offset, m_functor_0, m_functor_1);
```

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +      auto m_functor_0 = m_functor;
Same as above but probably don't need array :)

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +      handler(static_cast<size_t>(success));
Can just pass 0 in specifically here since we never repeat -- and success will always be 0.

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +//#if 0
Clean up dead code
```suggestion
```

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +#endif
Just search for `#if 0` we want to clean that up as it is dead code.

```suggestion
```

2025-05-06 15:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +//#if 0
```suggestion
```

2025-05-08 16:01 UTC, nmm0 commented on src/resilience/ErrorHandler.hpp
> +using unrecoverable_data_corruption_handler = std::function<void(std::size_t)>;
I think it should be reverted to "number of retries"; it's not inaccurate because it will always be 0. Since we plan on re-adding retries in the future this way any users wouldn't have to change their API.

2025-05-08 17:20 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +  auto MakeWrapper (int64_t work_size, int64_t offset, const FunctorType &m_functor_0, const FunctorType &m_functor_1) const{
Kokkos CamelCases classes (e.g. `Kokkos::Impl::DeepCopy`) but snake_case for functions (e.g. `Kokkos::deep_copy`)

2025-05-08 19:07 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +#endif
It's okay to do DMR in another PR but we shouldn't merge in dead code (like this)

2025-05-08 19:20 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
>        auto m_functor_1 = m_functor;
a std::array would generate identical code here so no difference in performance

2025-05-08 19:20 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResParallel.hpp
> +    }else if constexpr (!std::is_void_v<WorkTag>)
We decided to just manually do some of the formatting fixes as clang-format might generate a bunch of changes. We'll do that separately on the codebase in a different PR

2025-05-08 21:33 UTC, Matthew-Whitlock reviewed
I'm happy! Leaving it to Nic to do the approval

2025-05-15 20:21 UTC, nmm0 commented
> I'm happy! Leaving it to Nic to do the approval

@Matthew-Whitlock can you approve? Currently it still has you on requesting changes. Don't worry it won't be merged until I re-review :)

2025-05-15 21:25 UTC, Matthew-Whitlock approved these changes
Whoops - I feel like marking everything resolved should remove the request for changes

2025-05-15 22:01 UTC, nmm0 reviewed
Almost ready :)

2025-05-15 22:01 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +    size_t total_extent = original.extent(0) * original.extent(1);
Let's merge `Inject2D()` and `Inject1D()` into one function as this will break with views of rank > 2 (also need to make the name consistent with the style which is snake case for function names).

2025-05-29 19:36 UTC, nmm0 reviewed
Looks good, just a couple minor points/typos!

2025-05-29 19:36 UTC, nmm0 commented on src/resilience/exec_space/openMP/OpenMPResSubscriber.hpp
> +  size_t temp_numer = next_inject;
Can probably remove `temp_numer` and use `next_inject` directly

2025-05-29 19:36 UTC, nmm0 commented on tests/TestMain.cpp
> +  auto  ret = RUN_ALL_TESTS();
This looks accidental

2025-05-29 20:23 UTC, nmm0 approved these changes

2025-05-30 20:07 UTC, saibalde approved these changes
Looks good to me.

2025-06-02 13:30 UTC, merged